### ISSUE TITLE
WebSocket disconnects after 1 minute of inactivity

### ISSUE THREAD

**Issue by ItsJustSomeDude** [RodolfoFigueroa/ReplikaJS#2]
I noticed that if I connected my Replika to a channel and started talking immediately, everything worked fine.  However, if I stopped talking for exactly one minute, she would not get my messages anymore or respond, although the logs are clean.  I added a simple log message to `handlers.js` line 225 on the Websocket close event, and saw that it fired after exactly one minute of not sending any messages.

I then observed that the unmodified Replika web client also drops the websocket after exactly one minute, but it has reconnect logic, so the socket gets re-opened immediately afterwards.

I can think of two options: Sending some sort of event every 30 seconds to keep it open, or add re-connect logic, or both.  From looking at the web client, it appears we may be able to send the `chat_suggestions_list` event to refresh the socket.

Do you accept PRs on this repo?  If so, I could add one or both of these solutions and PR it.

Thank you for your time!

**Comment by RodolfoFigueroa** [comment]
Transferred to RodolfoFigueroa/Kopiya#1
