### ISSUE TITLE
Empty prompt

### ISSUE THREAD

**Issue by Hotohori** [RodolfoFigueroa/ReplikaJS#3]
I get the script locally to work, but when ever I write something in discord a complete empty prompt is send to Replika. All other stuff works flawless. The correct permissions are set, checked it several times now if I don't have overseen anything, but because there is send a empty prompt, the bot sees definitely my messages.

**Comment by ItsJustSomeDude** [comment]
This is likely due to Discord changing the Message Content to a privileged intent.  The bot will see the content as an empty string, so will send said empty string to Replika.

**Comment by RodolfoFigueroa** [comment]
Transferred to RodolfoFigueroa/Kopiya#2
